use serde_json::{Value, json};
use std::io::{self, IsTerminal, Read};
use std::path::{Component, Path, PathBuf};

pub fn run() -> Result<(), String> {
    if io::stdin().is_terminal() {
        return Err("rai guard is an internal hook command that expects JSON on stdin. It is called automatically by Codex and Claude Code; use rai sync or rai doctor for project commands.".into());
    }
    let mut input = String::new();
    io::stdin()
        .read_to_string(&mut input)
        .map_err(|e| e.to_string())?;
    let decision = serde_json::from_str::<Value>(&input)
        .map_err(|e| format!("Invalid projection guard input: {e}"))
        .and_then(|event| check(&event));
    let output = match decision {
        Ok(None) => json!({}),
        Ok(Some(reason)) | Err(reason) => json!({
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": reason
            }
        }),
    };
    println!("{output}");
    Ok(())
}

fn check(event: &Value) -> Result<Option<String>, String> {
    if event["hook_event_name"].as_str() != Some("PreToolUse") {
        return Err("Projection guard requires a PreToolUse event".into());
    }
    let tool = event["tool_name"]
        .as_str()
        .ok_or("Missing hook tool_name")?;
    if !matches!(tool, "apply_patch" | "Edit" | "Write" | "MultiEdit") {
        return Ok(None);
    }
    let cwd = PathBuf::from(event["cwd"].as_str().ok_or("Missing hook cwd")?);
    let root = match crate::find_repo(&cwd) {
        Ok(root) => root,
        Err(error) if error.starts_with("no .agents/ directory found") => return Ok(None),
        Err(error) => return Err(error),
    };
    let paths: Vec<_> = edit_paths(tool, &event["tool_input"])?
        .into_iter()
        .map(|path| resolve(&cwd.join(path)))
        .collect();
    // Let an agent repair invalid canonical resources; those resources are never
    // generated destinations, so they do not need projection validation first.
    if paths
        .iter()
        .all(|path| path.starts_with(root.join(".agents")))
    {
        return Ok(None);
    }
    let rules = crate::read_rules(&root)?;
    let outputs = crate::projection_outputs(&root, &rules)?;
    for path in paths {
        for (relative, _, _) in &outputs {
            if path == resolve(&root.join(relative)) {
                let destination = if relative == "AGENTS.md" || relative == "CLAUDE.md" {
                    ".agents/rules/ (global rules)".to_owned()
                } else if let Some(scope) = relative.strip_suffix("/AGENTS.md") {
                    format!(".agents/rules/ with path: {scope}")
                } else {
                    "the matching canonical resource under .agents/".to_owned()
                };
                return Ok(Some(format!(
                    "{relative} is generated by rai. Edit {destination}, then run rai sync. Direct edits to generated projections are blocked."
                )));
            }
        }
    }
    Ok(None)
}

fn edit_paths(tool: &str, input: &Value) -> Result<Vec<String>, String> {
    if tool != "apply_patch" {
        return input["file_path"]
            .as_str()
            .map(|path| vec![path.to_owned()])
            .ok_or_else(|| "Cannot inspect edit: missing file_path".into());
    }
    let patch = input
        .as_str()
        .or_else(|| input["input"].as_str())
        .or_else(|| input["patch"].as_str())
        .ok_or("Cannot inspect apply_patch input")?;
    let paths: Vec<String> = patch
        .lines()
        .filter_map(|line| {
            [
                "*** Add File: ",
                "*** Update File: ",
                "*** Delete File: ",
                "*** Move to: ",
            ]
            .iter()
            .find_map(|prefix| line.strip_prefix(prefix))
            .map(str::to_owned)
        })
        .collect();
    if paths.is_empty() {
        return Err("Cannot inspect apply_patch file paths".into());
    }
    Ok(paths)
}

fn resolve(path: &Path) -> PathBuf {
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::CurDir => {}
            Component::ParentDir => {
                normalized.pop();
            }
            other => normalized.push(other.as_os_str()),
        }
    }
    // Resolve aliases, including the existing parent of an Add File destination.
    let mut existing = normalized.as_path();
    while !existing.exists() {
        let Some(parent) = existing.parent() else {
            return normalized;
        };
        existing = parent;
    }
    existing
        .canonicalize()
        .map(|base| base.join(normalized.strip_prefix(existing).unwrap()))
        .unwrap_or(normalized)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_all_patch_targets_including_moves_and_deletes() {
        let input = json!({"input": "*** Begin Patch\n*** Update File: src/main.rs\n*** Move to: AGENTS.md\n*** Delete File: src/AGENTS.md\n*** Add File: .agents/rules/a.md\n*** End Patch"});
        assert_eq!(
            edit_paths("apply_patch", &input).unwrap(),
            [
                "src/main.rs",
                "AGENTS.md",
                "src/AGENTS.md",
                ".agents/rules/a.md"
            ]
        );
        assert!(edit_paths("apply_patch", &json!({})).is_err());
        assert!(edit_paths("Write", &json!({"content": "text"})).is_err());
    }
}
